var GIFS = ["http://gph.is/1JlbUJI","http://gph.is/1PwqGzO","http://gph.is/2jtC1gE","http://gph.is/2bufQgr","http://gph.is/2c5haHO",
"http://gph.is/ZoYRm9","http://gph.is/2FEkmZw","http://gph.is/1NnJLmb","http://gph.is/1USHgOv","http://gph.is/16OKOYP","http://gph.is/2jtC1gE",
"http://gph.is/2gzD2io","http://gph.is/2gAyiZV","https://gph.is/2ydOKt9","http://gph.is/2yeElNO","http://gph.is/1ZnF2MC",
"http://gph.is/20LHycN","http://gph.is/2lrj902","https://gph.is/1JiIwX3","http://gph.is/1ZpGJcC","http://gph.is/2jYtSfI",
"http://gph.is/1JhXSeF","http://gph.is/1JUXKDV","https://gph.is/1PZa751","http://gph.is/1TPSJ02","http://gph.is/1Zbx09z",
"http://gph.is/1USHCER","http://gph.is/2l1zkk9","http://gph.is/1USIfhs","http://gph.is/1Ji7GVO","http://gph.is/1nM4Mkx",
"http://gph.is/1JiavWV","https://gph.is/1TPSYYT","http://gph.is/1SxDnjX","http://gph.is/1USFywB","http://gph.is/1USIoSa",
"http://gph.is/2l1NMbM","http://gph.is/1ZhQXWU","http://gph.is/1USGukk","http://gph.is/1USJAVA","http://gph.is/1UT9cl6",
"http://gph.is/2jlSqh0","http://gph.is/2l1Uyyx","http://gph.is/2ksAMcS","http://gph.is/1KuIaj5","http://gph.is/1Q1Y8lC",
"http://gph.is/1ZYpgVu","http://gph.is/1UQKWzy","http://gph.is/1UQBrAo","http://gph.is/1EhpwIy","http://gph.is/1USyujz",
"http://gph.is/2jlOiNR","http://gph.is/1Z7LG4i","http://gph.is/1nLXfT0","http://gph.is/1SPigYF","http://gph.is/2kaFyyJ",
"http://gph.is/2kGh4tq","http://gph.is/1USGPUc","http://gph.is/2jlNtoo","http://gph.is/1USJduj","http://gph.is/2kGyztz",
"http://gph.is/1TIMqO7","https://gph.is/1UQxWK9","https://gph.is/2oq1ZPG","http://gph.is/2ugCiTt","http://gph.is/1E3gC1c",
"https://gph.is/1VV7rDL","http://gph.is/1PZan43","http://gph.is/1ZnKEGM","http://gph.is/2jlW7mR","http://gph.is/1nS1ixx",
"https://gph.is/2jlTKR3","http://gph.is/1TRYjik","http://gph.is/16OKOYP","http://gph.is/1CEQvws","http://gph.is/19iZj7E",
"https://gph.is/14t7RsD","http://gph.is/1jcQoso","http://gph.is/16xUpI3","http://gph.is/1aQbojB","https://gph.is/13kzW2z",
"http://gph.is/I9XUJK","http://gph.is/17KPdxc","http://gph.is/17VZ15K","http://gph.is/14t7Jtl","http://gph.is/16sUn3r",
"http://gph.is/I3xUzj","http://gph.is/1gQ9mGM","https://gph.is/1j7cN9J","http://gph.is/1nomg1h","http://gph.is/2mb0Ux8",
"https://gph.is/2rNdaUa","http://gph.is/1xPHG0v","http://gph.is/1SxrA58","http://gph.is/1nROHdG","https://gph.is/XJawwI",
"https://gph.is/1P8ovBr","https://gph.is/2hpYvKE","https://gph.is/1MeoXA3"]

